### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by mkgupta01** [Open-Source-Chandigarh/Hacktoberfest2022#1]
We need to create a README.md file that is beginner friendly.
- It should contain all the steps required to make a PR.
- it should tell about what Hackoctoberfest is and how one can contribute to it

**Comment by aanchalsharmaa1024** [comment]
I can do it . Plz assign it to me.

**Comment by harshit0571** [comment]
> I can do it . Plz assign it to me.

assigned it to you

**Comment by mkgupta01** [comment]
The README.md is already created with PR #2 .
We can close this issue for now .
cc @harshit0571

**Comment by harshit0571** [comment]
> The README.md is already created with PR #2 .
> We can close this issue for now .
> cc @harshit0571 

We can add how to contribute instructions in the readme file.

**Comment by harshit0571** [comment]
> > The README.md is already created with PR #2 .
> > We can close this issue for now .
> > cc @harshit0571 
> 
> We can add how to contribute instructions in the readme file.
> 
> 

Like fork push create branch etc.
This would be helpful for beginners.

**Comment by mkgupta01** [comment]
we can create another issue for that. That would be a good choice IMO

Should we add a new CONTRIBUTING.md or add the instruction on README itself ?

**Comment by harshit0571** [comment]
Thats a good idea.
We can create a new file for instructions and link to the main one.

**Comment by mkgupta01** [comment]
You can close this issue then.
