### ISSUE TITLE
Create CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by mkgupta01** [Open-Source-Chandigarh/Hacktoberfest2022#10]
We need to make a CONTRIBUTING.md file that contains step by step instruction on how to contribute to this project

**Comment by harshit0571** [comment]
It would be great if we create a folder named 'rules' and add it in there.
Then link it to the main readme.

**Comment by harshit0571** [comment]
> We need to make a CONTRIBUTING.md file that contains step by step instruction on how to contribute to this project

Should we assign it to the assigned person of the previous issue?👀
@mayankkuamr001

**Comment by mkgupta01** [comment]
> > We need to make a CONTRIBUTING.md file that contains step by step instruction on how to contribute to this project
> 
> Should we assign it to the assigned person of the previous issue?👀 @mayankkuamr001

Yess, I don't have any issue

**Comment by mkgupta01** [comment]
> It would be great if we create a folder named 'rules' and add it in there. Then link it to the main readme.

We just need 1 file i.e CONTRIBUTING.md so I don't think we need a folder. 
What are your thoughts on this @harshit0571

**Comment by harshit0571** [comment]
> > It would be great if we create a folder named 'rules' and add it in there. Then link it to the main readme.
> 
> We just need 1 file i.e CONTRIBUTING.md so I don't think we need a folder. 
> What are your thoughts on this @harshit0571  

Ok! No problem we can create in the home directory.

**Comment by harshit0571** [comment]
@aanchalsharmaa1024 do you want to work on this task.
We closed the previous issue.

**Comment by aanchalsharmaa1024** [comment]
yes ofcourse . 
assign it to me.

**Comment by aanchalsharmaa1024** [comment]
thanku @harshit0571

**Comment by mkgupta01** [comment]
Closed with PR #13
