### ISSUE TITLE
I want to add the copyright bar at the below side of the web page.

### ISSUE THREAD

**Issue by abhay-raj19** [Open-Source-Chandigarh/Hacktoberfest2022#16]
Preventing the website from copyright issues i want to add the copyright, terms and condition, about etc.  bar in the bottom most side of the web page. 
**Pls assign it me.**

![image](https://user-images.githubusercontent.com/96302417/195864056-45189cb8-1072-43ed-84db-3b505bdf4d91.png)
** LIKE THIS**
<img width="773" alt="image" src="https://user-images.githubusercontent.com/96302417/195863906-ba0a75e2-afdc-4e61-81f2-4f9429be1f1a.png">
which can help your website form been copyrighted. And will make it more unique.

**Comment by harshit0571** [comment]
Hi @abhay-raj19, thank you for showing interest.
But we don't have a website.
This repo is just a readme fiel that contains some open source projects

**Comment by abhay-raj19** [comment]
Hello Harshit

Actually i had just started up my journey into the open source community.So
for that i  thought to contribute in the hactoberfest 22.

So that's why i was contributing into your repository.


So i thought beginning with your repository and also participating in
Hactoberfest 22 would be a great opportunity for me.

Sir i will do my best.
Pls assign me the issue with the labels of Hactoberfest.

It would be a great opportunity for me.

**Comment by harshit0571** [comment]
you can contribute by adding more porjects in the readme file.
I will accept them
